name: mobile_poke_app
description: "Poke app Exercise for Mobile Module of IOET University Part 2"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  provider: ^5.0.0
  image_picker: ^1.0.1
  path: ^1.8.2
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pokemon_types/
    - assets/stats_types/
